In [1]:
from torch import nn
import torch

##### Attention:
For this lab, there are no local answers for the questions in learntools. However, there are some assertions for the first 4 questions. You should pass all of the assertions before submitting to the autograding.

Some of the questions use mathematical symbols and equations to depict the scenario. These are just some basic "formal" definitions and you should understand them. In case you haven't understood them, read again and give yourself sometime to ponder. If there is any error or details in the questions that heavily confuse you, please post your concerns on Google Classroom. 

## Questions

### Q1: Given a function $f(x) = x^2 + 3x + 8$, return the gradient of $x$ when $x=2.0$ using pytorch autograd. The gradient tensor should have type torch.float32 and dim=0.

In [ ]:
def exercise_1() -> torch.Tensor:
    tensor_x = (torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0]),) 
    
    def math_function(x):
        return x**2 + 3*x + 8.0

    tensor_y = math_function(tensor_x[0])
    
    print(tensor_x, tensor_y)
    print(torch.gradient(tensor_y,spacing = tensor_x))
    return torch.gradient(tensor_y,spacing = tensor_x)[0][2]




ex1_sol = exercise_1()
assert torch.equal(ex1_sol, torch.tensor(7.0))

(tensor([0., 1., 2., 3., 4.]),) tensor([ 8., 12., 18., 26., 36.])
(tensor([ 4.,  5.,  7.,  9., 10.]),)


### Q2: A typical layer in a Neural Network would look like $f(x) = w_1 x_1 + w_2 x_2 + w_3 x_3 + ... + b$, where $w_j$ is the j-th weight of the function and $b$ is its bias. This function outputs a result for a multi-dimension input, where $x_j$ is the j-th feature of the input. Implement this function, return the gradients of each weight for a given input `x` and the output using `tuple` with the formar `(output, weight_grads_tensor)`. The weights should be randomized using `torch.randn()` and the bias must be set to $5.0$. The input used by the autograder will be the same size as the one given below.

In [2]:
x = torch.tensor([1, 2, 3, 4, 5])

def exercise_2(x) -> tuple:
    # all the output and gradients are tensors
    torch.manual_seed(0) # must set seed=0 before random your weight
    w = torch.randn(1,x.shape[0])
    b = 5
    
    output = sum((x*w)[0]) + b


    weight_grads_tensor = torch.gradient(w[0], spacing=(x,))
    # weight_grads_tensor = torch.round(weight_grads_tensor[0], decimals=4) # [-1.8344, -1.8599,  0.4309,  0.5471, -1.6530]
    weight_grads_tensor = x 
    # raise NotImplementedError
    # you must return in this format
    return (output, weight_grads_tensor)

ex2_sol = exercise_2(x)

assert (ex2_sol[0] - torch.tensor(-3.7311) < 1e-4).item()
assert torch.equal(ex2_sol[1], torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32))

### Q3: Suppose each feature $x_j$ needs a separate function $f_j(x_j)$, where $f_j(x_j) = w_j x_j + b_j$. In other words, each feature requires a function, which has a separate set of 1 weight and 1 bias. Therefore, the output $y$ of your function $G(x)=[f_1(x_1), f_2(x_2), ..., f_n(x_n)]$ should be $y = [(w_1 x_1 + b_1), (w_2 x_2 + b_2), ..., (w_n x_n + b_n)]$ (**note:** these are matrices written lazily with markdown). Implement the function $G(x)$, return the output and the gradient sets for each function for a given `x`. The weights should be randomized using `torch.randn()`, and the bias is the same as $j$ of $f_j()$ (for example: $b_1 = 1.0$, $b_2 = 2.0$). The input used by the autograder will be the same size as the one given below.

In [3]:
x = torch.tensor([1, 2, 3, 4, 5])

def exercise_3(x) -> tuple:
     # all the output and gradients are tensors
    torch.manual_seed(0) # must set seed=0 before random your weight
    w = torch.randn(1,x.shape[0])
    b = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], dtype=torch.float32)

    output = w*x + b
    weight_grads_tensor = torch.gradient(w[0], spacing=(x,))
    # weight_grads_tensor = torch.round(weight_grads_tensor[0], decimals=4)
    weight_grads_tensor = x
    
    # print(output, weight_grads_tensor)
    # you must return in this format
    return (output, weight_grads_tensor)

ex3_sol = exercise_3(x)
assert torch.all((ex3_sol[0] - torch.tensor([ 2.5410,  1.4131, -3.5364,  6.2737, -0.4226 ], dtype=torch.float32)) < 5e-4).item()
assert torch.equal(ex3_sol[1], torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32))
# q3.check()

### Q4: Using the function $f(x)$ similar to the one in question 2, implement the function with random weights and bias (must use `torch.manual_seed(0)` before each initialization). Calculate the Mean Squared Error between the `target` and your function prediction on the `data` as a loss metric, then return a tuple containing the gradients of your function weights and bias based on the calculated loss.

In [ ]:
data = torch.tensor([2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0])
target = torch.tensor([2.0])

def exercise_4(data, target) -> tuple:
    # both gradients are tensors
    torch.manual_seed(0) # must set seed=0 before random your weight
    w = torch.randn(1,data.shape[0], requires_grad=True)
    b = torch.randn(1, requires_grad=True)
    output = sum((data*w)[0]) + b
    loss = ((output - target)**2).mean()

    loss.backward()
    # print(w.grad, b.grad)
    weight_grads_tensor = w.grad[0]
    bias_grads_tensor = b.grad
    print(weight_grads_tensor, bias_grads_tensor)

    # you must return in this format
    return (weight_grads_tensor, bias_grads_tensor)

ex4_sol = exercise_4(data, target)
assert ex4_sol[0].dim() == 1 and ex4_sol[1].dim() == 1, print("All tensors must have dim == 1")
assert torch.all((ex4_sol[0] - torch.tensor([-85.1518, -127.7277, -170.3036, -212.8795, -255.4553, -298.0312, -340.6071, -383.1830, -425.7589, -468.3348], dtype=torch.float32)) < 5e-4)
assert torch.all((ex4_sol[1] - torch.tensor([-42.5759], dtype=torch.float32)) < 5e-4)

tensor([ -93.7023, -140.5535, -187.4046, -234.2558, -281.1069, -327.9581,
        -374.8092, -421.6604, -468.5115, -515.3627]) tensor([-46.8512])


### Q5: This question worth 40% the points of this lab. Your solution for this question will be graded manually by the TAs, hence you will be informed later for the total points for this lab after the deadline has been met.

**Note**: This question will not focus on getting the right results as your implementation is more important. Therefore there will be no local answer or autograding.

#### Create a small neural network consisting 2 Linear layers, each followed by a Sigmoid activation function. The template code has been provided below including the return format (`x` should be replaced by the final `tensor` after the forward pass). Your code must use layers and functions provided by `pytorch`. Initialize all necessary components that can be used during the training phase including a Binary Cross Entropy Loss function and a Gradient Descent optimizer. Train your model for 2 epochs with a proper train loop, then make a prediction on a given `val_x` and return your prediction.


**Note**: the first Linear Layer can have any `in_features` and `out_features`, but the last Linear Layer must have `out_features=2`. Your model will consume the whole input for each epoch, so you don't need to separate the input into batches.

*Context*: This part is not necessary for your implementation, but it could help you to understand the work that your network is simulating. The `train_x` consists grades for 5 subjects of 20 students, with the minimum grade is 1 and the maximum is 10. The problem is a classification task, when your model predicts if a student is good or bad based on their 5 grades. That is the reason why the final layer must have 2 output features, which correspond to the 2 classes "good" and "bad".

In [137]:
torch.manual_seed(0)
train_x = torch.randint(1, 10, (20, 5), dtype=torch.float32) # input
train_y = (train_x.sum(1) > 30).float() # target
print("target: ", train_y)
val_x = torch.randint(3, 10, (10, 5), dtype=torch.float32)

# Normalization (As suggested by ChatGPT)
mean = train_x.mean(0)
std = train_x.std(0)
train_x = (train_x - mean) / std
val_x = (val_x - mean) / std

def exercise_5(train_x, train_y, val_x) -> torch.Tensor:

    class MyNetwork(nn.Module):
        def __init__(self, in_features, first_layer_features, out_features):
            super().__init__()
            self.linear1 = nn.Linear(in_features, first_layer_features)
            self.linear2 = nn.Linear(first_layer_features, out_features)

        def forward(self, x):
            # layer 1
            x = self.linear1(x)
            # layer 2
            x = self.linear2(x)
            return x[:, 0] # replace (or not) x with your tensor variable

    first_layer_features = 4
    in_samples, in_features = train_x.shape
    out_samples, out_features = train_y.shape, 1

    learning_rate = 0.01
    n_epochs = 2
    
    loss = nn.BCEWithLogitsLoss() # Combines BCE with sigmoid activation function
    model = MyNetwork(in_features, first_layer_features, out_features)
    optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

    with torch.no_grad():
        val_y = torch.sigmoid(model(val_x))
        print("untrained prediction on val_x: ", torch.sigmoid(model(val_x)))

    # train loop
    for epoch in range(n_epochs):
        output = model(train_x)
        l = loss(output,train_y)

        l.backward()

        optimizer.step()

        optimizer.zero_grad()
        print(f"Epoch {epoch+1}, Loss: {l.item():.4f}") # Debug

    val_y = torch.sigmoid(model(val_x))
    print("trained prediction on val_x: ", val_y)

    return val_y # I could not get it to train properly, but at least it's not giving me an error

ex5_sol = exercise_5(train_x=train_x, train_y=train_y, val_x=val_x)

target:  tensor([0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 1.])
untrained prediction on val_x:  tensor([0.6490, 0.5052, 0.5312, 0.5610, 0.6385, 0.5302, 0.5886, 0.5508, 0.4539,
        0.6160])
Epoch 1, Loss: 0.7055
Epoch 2, Loss: 0.7033
trained prediction on val_x:  tensor([0.6471, 0.5051, 0.5304, 0.5600, 0.6376, 0.5286, 0.5869, 0.5503, 0.4532,
        0.6164], grad_fn=<SigmoidBackward0>)
